# fly.toml app configuration file generated for jhigh-portfolio on 2023-09-29T13:51:10-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "jhigh-portfolio"
primary_region = "den"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
