import { Profile } from "./types";
import { Project } from "./types";

export const profile_db: Profile = {
  languages: [
    "Rust",
    "Python",
    "Golang",
    "TypeScript",
    "JavaScript",
    "HTML/CSS",
    "SQL",
    "C++",
    "C",
    "Fortran",
    "Bash",
  ],
  technologies: [
    "Actix",
    "AG Grid",
    "Boto",
    "Docker",
    "FastAPI",
    "Git",
    "GlueSQL",
    "Go-Kit",
    "Great Expectations",
    "HTMX",
    "js-sys",
    "Kubernetes",
    "Mangum",
    "Moto",
    "Next",
    "Ngnix",
    "Node",
    "npm",
    "Pandas",
    "Polars",
    "PostgreSQL",
    "Prisma",
    "PyTest",
    "React",
    "Redis",
    "Rocket",
    "Serde",
    "Skeleton UI",
    "SPARK",
    "SQLite",
    "Svelte/SvelteKit",
    "Tailwind CSS",
    "Tauri",
    "Threlte",
    "Tokio",
    "Tox",
    "Trunk",
    "Visual Studio",
    "VS Code",
    "wasm-bindgen",
    "web-sys",
    "Yarn",
    "Yew",
    "AWS ALB",
    "AWS Amplify",
    "AWS API Gateway",
    "AWS Athena",
    "AWS Aurora",
    "AWS Batch",
    "AWS CDK",
    "AWS Cloud Formation",
    "AWS CloudWatch",
    "AWS CodeArtifact",
    "AWS Codebuild",
    "AWS CodePipeline",
    "AWS CodeStar",
    "AWS Cognito",
    "AWS DynamoDB",
    "AWS ECR",
    "AWS ECS",
    "AWS EKS",
    "AWS EventBridge",
    "AWS Fargate",
    "AWS Glue",
    "AWS IAM",
    "AWS Lambda",
    "AWS QuickSight",
    "AWS RDS",
    "AWS Redshift",
    "AWS Route53",
    "AWS S3",
    "AWS SDK",
    "AWS SecretsManager",
    "AWS SQS",
    "AWS Step Functions",
    "AWS VPC",
  ],
  other: [
    "Agile",
    "BDD",
    "Biscuit auth",
    "CI/CD",
    "Clean Code",
    "Cloud-native Software Design",
    "Data Engineering",
    "Design Patterns",
    "DevOps",
    "FP",
    "HPC",
    "JWT",
    "Oauth2",
    "OOP",
    "Parallel Programming",
    "Serverless",
    "Client-Server Architecture",
    "Event-driven Archetecture",
    "Layered Architecture",
    "Microservices Architecture",
    "MVC",
    "REST",
    "TDD",
  ],
};

export const project_db: Project[] = [
  {
    title: "A Contacts Web Application",
    description:
      "This web-application provides a simple interface for users to manage a list of contacts. A user may login or register, and then add, update, and delete their contacts. The user, along with their contacts information are stored on a database backend. The project consists of two code repositories, (1) a backend written in Rust, and (2) a frontend written in TypeScript with React. The backend only accepts requests from a frontend instance via CORS. Furthermore, CRUD operations are only allowed if the cient passes a valid biscuit token with their requests. The only endpoint that does not require a token is the login endpoint, but this is still protected through CORS. The backend database is a SQLite database managed by the Prisma Rust CLI. The Prisma CLI takes as input a schema for users and contacts and produces Rust modules importable and usable within REST endpoints exposed through Actix-web. In this way it is simple to perform all kinds of database operations within endpoint logic.",
    languages: ["Rust", "Typescript"],
    technologies: [
      "React",
      "Material UI",
      "Actix Web",
      "Biscuit auth",
      "REST",
      "SQLite",
      "Prisma",
    ],
    links: [
      "https://github.com/judahhigh/contacts-frontend",
      "https://github.com/judahhigh/contacts-backend",
    ],
    id: "contactswebapp",
  },
  {
    title: "An E-Commerce Store",
    description:
      "This project consists of two parts. First is a microservice architecture to support everything related to a common e-commerce store application like Amazon. It needs to handle user registration and login, search, transactions, vendor information and pages, customer support, settings, etc. I was interested in showcasing how one might create a microservice architecture to handle all of this. Second is a e-commerce store frontend to effectuate everything a user or vendor might want to do on an e-commerce store. It's by no means a small project and will take time to complete. Regardless, it's given me a chance to use a popular server-side language like Go to build it. It also gave me the opportunity to work with cloud infrastructure, and container orchestration systems powered by Docker and Kubernetes. I'm also getting to experiment with REST, gRCP, message broking through RabbitMQ, and more. For the frontend I'm choosing to use TypeScript with Svelte and SvelteKit, which from my previous experience lends itself to creating extremely well-organized fully featured client applications. This project is truly a challenge, but a worthwhile one at that.",
    languages: ["Go", "TypeScript"],
    technologies: [
      "Svelte",
      "SvelteKit",
      "Skeleton UI",
      "Go-Kit",
      "JWT",
      "REST",
      "gRCP",
      "Microservices",
      "Docker",
      "Kubernetes",
      "RabbitMQ",
      "PostgreSQL",
    ],
    links: ["https://github.com/judahhigh/estore-backend"],
    id: "e-commerce-store",
  },
  {
    title: "Portfolio, this website",
    description:
      "This website gave me a chance to work with an emerging technology called HTMX, that stands for HTML extensions. It is a library to powerup plain-old HTML with new powers that gives the frontend dev the opportunity of avoiding JavaScript and the endless land of JavaScript dependencies. Serving the website with Bun, and Elysia, allowed me to create an incredibly simple and responsive website as well. Not only this, but with Tailwind CSS I had the chance to make plain-old HTML look good with class decorating only. This website allows me to showcase my skills, personal projects, learning experiences, and interests. Perusing this website should show that I am an incredibly driven and curious person software engineer. I get deep fulfillment from pushing my own boundaries, staying ahead of industry shifts, learning new technologies, and making the most of my career as a budding software engineer.",
    languages: ["TypeScript"],
    technologies: ["HTMX", "Tailwind CSS", "Bun"],
    links: ["https://github.com/judahhigh/portfolio"],
    id: "portfolio",
  },
];
