import { Profile } from "./types";
import { Project } from "./types";

export const profile_db: Profile = {
  languages: [
    "Rust",
    "Python",
    "Golang",
    "TypeScript",
    "JavaScript",
    "HTML/CSS",
    "SQL",
    "C++",
    "C",
    "Fortran",
    "Bash",
  ],
  technologies: [
    "Actix",
    "AG Grid",
    "Boto",
    "Docker",
    "FastAPI",
    "Git",
    "GlueSQL",
    "Go-Kit",
    "Great Expectations",
    "HTMX",
    "js-sys",
    "Kubernetes",
    "Mangum",
    "Moto",
    "Next",
    "Ngnix",
    "Node",
    "npm",
    "Pandas",
    "Polars",
    "PostgreSQL",
    "Prisma",
    "PyTest",
    "React",
    "Redis",
    "Rocket",
    "Serde",
    "Skeleton UI",
    "SPARK",
    "SQLite",
    "Svelte/SvelteKit",
    "Tailwind CSS",
    "Tauri",
    "Threlte",
    "Tokio",
    "Tox",
    "Trunk",
    "Visual Studio",
    "VS Code",
    "wasm-bindgen",
    "web-sys",
    "Yarn",
    "Yew",
    "AWS ALB",
    "AWS Amplify",
    "AWS API Gateway",
    "AWS Athena",
    "AWS Aurora",
    "AWS Batch",
    "AWS CDK",
    "AWS Cloud Formation",
    "AWS CloudWatch",
    "AWS CodeArtifact",
    "AWS Codebuild",
    "AWS CodePipeline",
    "AWS CodeStar",
    "AWS Cognito",
    "AWS DynamoDB",
    "AWS ECR",
    "AWS ECS",
    "AWS EKS",
    "AWS EventBridge",
    "AWS Fargate",
    "AWS Glue",
    "AWS IAM",
    "AWS Lambda",
    "AWS QuickSight",
    "AWS RDS",
    "AWS Redshift",
    "AWS Route53",
    "AWS S3",
    "AWS SDK",
    "AWS SecretsManager",
    "AWS SQS",
    "AWS Step Functions",
    "AWS VPC",
  ],
  other: [
    "Agile",
    "BDD",
    "Biscuit auth",
    "CI/CD",
    "Clean Code",
    "Cloud-native Software Design",
    "Data Engineering",
    "Design Patterns",
    "DevOps",
    "FP",
    "HPC",
    "JWT",
    "Oauth2",
    "OOP",
    "Parallel Programming",
    "Serverless",
    "Client-Server Architecture",
    "Event-driven Archetecture",
    "Layered Architecture",
    "Microservices Architecture",
    "MVC",
    "REST",
    "TDD",
  ],
};

export const project_db: Project[] = [
  {
    title: "Contacts",
    description:
      "This web-application provides a simple interface for users to manage a list of contacts. A user may login or register, and then add, update, and delete their contacts. The user, along with their contacts information are stored on a database backend. The project consists of two code repositories, (1) a backend written in Rust, and (2) a frontend written in TypeScript with React. The backend only accepts requests from a frontend instance via CORS. Furthermore, CRUD operations are only allowed if the cient passes a valid biscuit token with their requests. The only endpoint that does not require a token is the login endpoint, but this is still protected through CORS. The backend database is a SQLite database managed by the Prisma Rust CLI. The Prisma CLI takes as input a schema for users and contacts and produces Rust modules importable and usable within REST endpoints exposed through Actix-web. In this way it is simple to perform all kinds of database operations within endpoint logic.",
    languages: ["Rust", "Typescript"],
    technologies: [
      "React",
      "Material UI",
      "Actix Web",
      "Biscuit auth",
      "REST",
      "SQLite",
      "Prisma"
    ],
    links: [
      "https://github.com/judahhigh/contacts-frontend",
      "https://github.com/judahhigh/contacts-backend",
    ],
  },
  {
    title: "E-Commerce Store",
    description: "A fully featured E-commerce store.",
    languages: ["Go", "TypeScript"],
    technologies: [
      "Svelte",
      "SvelteKit",
      "Skeleton UI",
      "Go-Kit",
      "JWT",
      "REST",
      "gRCP",
      "Microservices",
      "Docker",
      "Kubernetes",
      "RabbitMQ",
      "PostgreSQL",
    ],
    links: ["https://github.com/judahhigh/estore-backend"],
  },
  {
    title: "Portfolio",
    description: "Static webpage to display information about myself.",
    languages: ["TypeScript"],
    technologies: ["HTMX", "Tailwind CSS", "Bun"],
    links: ["https://github.com/judahhigh/portfolio"],
  },
];
